# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtQemu.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(590, 224)
        MainWindow.setMinimumSize(QtCore.QSize(590, 0))
        MainWindow.setMaximumSize(QtCore.QSize(590, 224))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 2, QtCore.Qt.AlignVCenter)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 3, 1, 1, 1, QtCore.Qt.AlignRight)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 3, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 1, 1, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 590, 29))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.actionby_Nickolsky = QtWidgets.QAction(MainWindow)
        self.actionby_Nickolsky.setObjectName("actionby_Nickolsky")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.menu.addAction(self.action)
        self.menu.addAction(self.action_2)
        self.menu_2.addAction(self.actionby_Nickolsky)
        self.menu_3.addAction(self.action_3)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "qtQEMU"))
        self.label_2.setText(_translate("MainWindow", "Моя виртуальная машина"))
        self.pushButton.setText(_translate("MainWindow", "Запустить"))
        self.comboBox.setItemText(0, _translate("MainWindow", "512"))
        self.comboBox.setItemText(1, _translate("MainWindow", "1024"))
        self.comboBox.setItemText(2, _translate("MainWindow", "2048"))
        self.pushButton_2.setText(_translate("MainWindow", "Выбрать"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", " Путь до машины"))
        self.label.setText(_translate("MainWindow", "Выделить ОЗУ"))
        self.menu.setTitle(_translate("MainWindow", "Создать"))
        self.menu_2.setTitle(_translate("MainWindow", "Автор"))
        self.menu_3.setTitle(_translate("MainWindow", "Действия"))
        self.action.setText(_translate("MainWindow", "Новый диск"))
        self.action_2.setText(_translate("MainWindow", "Новая виртуальная машина"))
        self.actionby_Nickolsky.setText(_translate("MainWindow", "by Nickolsky"))
        self.action_3.setText(_translate("MainWindow", "Удалить"))
